AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple example of a Lambda function and a DynamoDB table with read/write access.

Resources:
  # DynamoDB Table Resource
  MyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKeyName: id
      PrimaryKeyType: String
      # Optional: ProvisionedThroughput:
      #   ReadCapacityUnits: 5
      #   WriteCapacityUnits: 5

  # Lambda Function Resource
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x # Choose your desired runtime
      Handler: src/app.handler # Adjust the handler path as necessary
      Environment:
        Variables:
          TABLE_NAME: !Ref MyTable # Pass the table name to the Lambda function
      Connectors:
        MyConn:
          Properties:
            Destination:
              Id: MyTable
            Permissions:
              - Read
              - Write
      # Optional: Use Policies property instead of Connectors for more granular control
      # Policies:
      #   - DynamoDBReadWritePolicy:
      #       TableName: !Ref MyTable

