AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SAM CLI Nested Stack for Auto Dependency Layer Creation
Metadata:
  SamCliInfo: 1.147.1
  key: AWS SAM CLI sync command
Outputs:
  LexFulfillmentLambda69f56d60DepLayer:
    Value:
      Ref: LexFulfillmentLambda69f56d60DepLayer
Resources:
  LexFulfillmentLambda69f56d60DepLayer:
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      CompatibleRuntimes:
      - python3.12
      ContentUri: C:\Users\dunca\OneDrive\Documents\Personal Project - Smart Journal\MyServerlessApp\.aws-sam\auto-dependency-layer\LexFulfillmentLambda69f56d60DepLayer
      Description: Auto created layer for dependencies of function LexFulfillmentLambda
      LayerName: Smart-Journal-Stf29fe257-LexFulfillmentLambda69f56d60-DepLayer
      RetentionPolicy: Delete
    Type: AWS::Serverless::LayerVersion
Transform: AWS::Serverless-2016-10-31
